### ISSUE TITLE
Error in Newsfeed module

### ISSUE THREAD

**Issue by sebcaps** [MichMich/MagicMirror#1091]
**Platform**:  raspberry3 

**Node Version**: 6.12.0

**MagicMirror Version**: V2

**Description**: error in Feeds module

**Steps to Reproduce**: configure feed module to use [http://rss.liberation.fr/rss/latest/](http://rss.liberation.fr/rss/latest/) source. 

**Expected Results**: Data are displayed

**Actual Results**:  error raised at startup
`Whoops! There was an uncaught exception...
TypeError: description.replace is not a function
    at EventYoshi.<anonymous> (/home/pi/MagicMirror/modules/default/newsfeed/fetcher.js:54:31)
    at emitOne (events.js:96:13)
    at EventYoshi.emit (events.js:191:7)
    at SAXStream.wrapper.__wrappers.(anonymous function) (/home/pi/MagicMirror/node_modules/eventyoshi/lib/index.js:105:14)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:191:7)
    at SAXStream.onclosetag (/home/pi/MagicMirror/node_modules/feedme/lib/xmlfeedparser.js:153:14)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:191:7)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:258:17)
`

**Configuration**: `		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title : "Libé",
						url:"http://rss.liberation.fr/rss/latest/"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			},
		},`

**Additional Notes**: actually fail on first empty 'summary' tag. (there is  `<summary type="html"></summary>` in returned result)
Update line 54 of nodeFetcher.js  to `description = description.**toString()**.replace(regex, "");` do the trick, but I don't know if it's the best solution ;-)

**Comment by MichMich** [comment]
Fix merged.
