### ISSUE TITLE
Problems loading RSS module

### ISSUE THREAD

**Issue by Vicvares** [MichMich/MagicMirror#1098]
Hi, I'm currently having an issue with RSS news, here is the information. Thanks!

**Platform**: Raspberry Pi 3

**Node Version**: Version 0.12.13 or later.

**MagicMirror Version**: Latest

**Description**:  When I run the magic mirror, everything works well but RSS is not loading its content,, it stays at Loading...

If I check the terminal this is what I have:

> Whoops! There was an uncaught exception...
> TypeError: parser.close is not a function
>     at SAXStream.openf1 (/home/pi/MagicMirror/node_modules/feedme/lib/xmlfeedparser.js:107:14)
>     at emitOne (events.js:96:13)
>     at SAXStream.emit (events.js:191:7)
>     at SAXParser.me._parser.(anonymous function) [as onopentag] (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:258:17)
>     at emit (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:624:35)
>     at emitNode (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:629:5)
>     at openTag (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:825:5)
>     at SAXParser.write (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:1391:13)
>     at SAXStream.write (/home/pi/MagicMirror/node_modules/sax/lib/sax.js:239:18)
>     at module.exports.yoshi.write (/home/pi/MagicMirror/node_modules/feedme/lib/feedme.js:41:14)
> MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> 

**Steps to Reproduce**: I just ran DISPLAY=:0 npm start as I normally do

**Expected Results**: RSS news will be displayed a the bottom of the screen

**Actual Results**: A Loading... message stays at the bottom of the screen

**Configuration**:  This is the RSS section

},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "La Nacion",
						url: "http://www.nacion.com/rss/latest/?contentType=NWS"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

**Additional Notes**: None

**Comment by Vicvares** [comment]
The problem was with the RSS server
