### ISSUE TITLE
Can't Start the App

### ISSUE THREAD

**Issue by TillWae** [MichMich/MagicMirror#1160]
I updated the Mirror yesterday.
Since then I can not start the program anymore.

pm2 returns the error

================================================
0|mm       | npm ERR! Tell the author that this fails on your system:
0|mm       | npm ERR!     sh run-start.sh
0|mm       | npm ERR! You can get information on how to open an issue for this project with:
0|mm       | npm ERR!     npm bugs magicmirror
0|mm       | npm ERR! Or if that isn't available, you can get their info via:
0|mm       | npm ERR!     npm owner ls magicmirror
0|mm       | npm ERR! There is likely additional logging output above.
0|mm       | [1065:1105/033651.018590:FATAL:bus.cc(1197)] D-Bus connection was disconnected. Aborting.
0|mm       | #0 0x0000011d2e0c <unknown>
0|mm       | #1 0x0000011bf13a <unknown>
0|mm       | #2 0x000001fcb6c6 <unknown>

================================================

How can i fix this?

**Comment by TillWae** [comment]
My .log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'bugs', 'magicmirror' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 silly fetchPackageMetaData magicmirror
6 silly fetchNamedPackageData magicmirror
7 silly mapToRegistry name magicmirror
8 silly mapToRegistry using default registry
9 silly mapToRegistry registry https://registry.npmjs.org/
10 silly mapToRegistry data Result {
10 silly mapToRegistry   raw: 'magicmirror',
10 silly mapToRegistry   scope: null,
10 silly mapToRegistry   escapedName: 'magicmirror',
10 silly mapToRegistry   name: 'magicmirror',
10 silly mapToRegistry   rawSpec: '',
10 silly mapToRegistry   spec: 'latest',
10 silly mapToRegistry   type: 'tag' }
11 silly mapToRegistry uri https://registry.npmjs.org/magicmirror
12 verbose request uri https://registry.npmjs.org/magicmirror
13 verbose request no auth needed
14 info attempt registry request try #1 at 17:41:51
15 verbose request id 62ec57a72304286a
16 verbose etag "56fbae0b-bef"
17 verbose lastModified Wed, 30 Mar 2016 10:44:27 GMT
18 http request GET https://registry.npmjs.org/magicmirror
19 http 304 https://registry.npmjs.org/magicmirror
20 verbose headers { date: 'Sun, 28 Jan 2018 16:41:51 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"56fbae0b-bef"',
20 verbose headers   age: '405',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ams4427-AMS',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1517157712.773801,VS0,VE1',
20 verbose headers   vary: 'Accept-Encoding, Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 28 Jan 2018 16:41:51 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"56fbae0b-bef"',
21 silly get     age: '405',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ams4427-AMS',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1517157712.773801,VS0,VE1',
21 silly get     vary: 'Accept-Encoding, Accept' } ]
22 verbose etag https://registry.npmjs.org/magicmirror from cache
23 verbose get saving magicmirror to /home/pi/.npm/registry.npmjs.org/magicmirror/.cache.json
24 verbose correctMkdir /home/pi/.npm correctMkdir not in flight; initializing
25 silly bugs url https://github.com/MichMich/MagicMirror/issues
26 verbose stack Error: Command failed: xdg-open https://github.com/MichMich/MagicMirror/issues
26 verbose stack /usr/bin/xdg-open: 1: eval: www-browser: not found
26 verbose stack /usr/bin/xdg-open: 1: eval: links2: not found
26 verbose stack /usr/bin/xdg-open: 1: eval: elinks: not found
26 verbose stack /usr/bin/xdg-open: 1: eval: links: not found
26 verbose stack /usr/bin/xdg-open: 1: eval: lynx: not found
26 verbose stack /usr/bin/xdg-open: 1: eval: w3m: not found
26 verbose stack xdg-open: no method available for opening 'https://github.com/MichMich/MagicMirror/issues'
26 verbose stack
26 verbose stack     at ChildProcess.exithandler (child_process.js:198:12)
26 verbose stack     at emitTwo (events.js:106:13)
26 verbose stack     at ChildProcess.emit (events.js:191:7)
26 verbose stack     at maybeClose (internal/child_process.js:920:16)
26 verbose stack     at Socket.<anonymous> (internal/child_process.js:351:11)
26 verbose stack     at emitOne (events.js:96:13)
26 verbose stack     at Socket.emit (events.js:188:7)
26 verbose stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
27 verbose cwd /home/pi
28 error Linux 4.9.35-v7+
29 error argv "/usr/bin/node" "/usr/bin/npm" "bugs" "magicmirror"
30 error node v6.11.5
31 error npm  v3.10.10
32 error code 3
33 error Command failed: xdg-open https://github.com/MichMich/MagicMirror/issues
33 error /usr/bin/xdg-open: 1: eval: www-browser: not found
33 error /usr/bin/xdg-open: 1: eval: links2: not found
33 error /usr/bin/xdg-open: 1: eval: elinks: not found
33 error /usr/bin/xdg-open: 1: eval: links: not found
33 error /usr/bin/xdg-open: 1: eval: lynx: not found
33 error /usr/bin/xdg-open: 1: eval: w3m: not found
33 error xdg-open: no method available for opening 'https://github.com/MichMich/MagicMirror/issues'
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by TillWae** [comment]
Found the issue.
Java 7 was broken
