### ISSUE TITLE
Cannot render footer in the forum

### ISSUE THREAD

**Issue by fewieden** [MichMich/MagicMirror#1298]
By accessing any page in the forum, it only displays:

```
Render failed for template /home/forge/forum.magicmirror.builders/build/public/templates/footer.js:
 TypeError: Render failed for template /home/forge/forum.magicmirror.builders/build/public/templates/footer.js:
 templateFunction is not a function
    at runtime (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/runtime.js:64:16)
    at render (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/express.js:11:20)
    at Object.__express (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/express.js:33:5)
    at /home/forge/forum.magicmirror.builders/src/webserver.js:157:15
    at async.waterfall.Benchpress.precompile.source (/home/forge/forum.magicmirror.builders/src/middleware/index.js:226:12)
    at nextTask (/home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:5310:14)
    at next (/home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:5317:9)
    at /home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:958:16
    at /home/forge/forum.magicmirror.builders/src/file.js:146:3
    at /home/forge/forum.magicmirror.builders/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by el97** [comment]
Same here. What browser do you use?

**Comment by fewieden** [comment]
It's not browser related, that's a server issue.

**Comment by MichMich** [comment]
@paviro

**Comment by weaklion** [comment]
i want get solution.

**Comment by fewieden** [comment]
works again

**Comment by Wolfieeewolf** [comment]
Broken again

Render failed for template /home/forge/forum.magicmirror.builders/build/public/templates/footer.js:
 TypeError: Render failed for template /home/forge/forum.magicmirror.builders/build/public/templates/footer.js:
 templateFunction is not a function
    at runtime (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/runtime.js:64:16)
    at render (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/express.js:11:20)
    at Object.__express (/home/forge/forum.magicmirror.builders/node_modules/benchpressjs/build/lib/express.js:33:5)
    at /home/forge/forum.magicmirror.builders/src/webserver.js:157:15
    at async.waterfall.Benchpress.precompile.source (/home/forge/forum.magicmirror.builders/src/middleware/index.js:226:12)
    at nextTask (/home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:5310:14)
    at next (/home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:5317:9)
    at /home/forge/forum.magicmirror.builders/node_modules/async/dist/async.js:958:16
    at /home/forge/forum.magicmirror.builders/src/file.js:146:3
    at /home/forge/forum.magicmirror.builders/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by fewieden** [comment]
just checked it, seems to work again :D

**Comment by roramirez** [comment]
I did a rebuild of assets files in the  server. One hour before, and apparently is working now. Please, check is work for you. Thanks for report.

**Comment by el97** [comment]
It works for me now.

**Comment by MichMich** [comment]
@Wolfieeewolf Does it work for you now?

**Comment by Wolfieeewolf** [comment]
Working again :) Sorry working night shifts and couldn't reply until now.

**Comment by MichMich** [comment]
Thanks! Closing topic.
