### ISSUE TITLE
listening email issue

### ISSUE THREAD

**Issue by mizbanhadi** [MichMich/MagicMirror#1316]
NEW MAIL
NEW MAIL
NEW MAIL
listening for emails...
NEW MAIL
NEW MAIL
NEW MAIL
listening for emails...
NEW MAIL
NEW MAIL
NEW MAIL
listening for emails...
Whoops! There was an uncaught exception...
TypeError: Cannot read property 'id' of null
    at /home/pi/MagicMirror/modules/email/node_helper.js:42:44
    at Array.forEach (native)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/email/node_helper.js:41:42)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by MichMich** [comment]
Thanks for opening an issue!

To allow us to help you it's extremely important that we have all the details about your setup. During the creation of this issue, important details were asked to fill in. Because you did not provide (any) of these details we are unable to help you. 

If you are running into errors, please provide as many detailed error logs as possible in addition to the requested details.

If you are unaware how to retrieve all the requested information, feel free to ask for help on http://forum.magicmirror.builders.

This issue will be closed. Feel free to open a new issue with all the requested information.
