### ISSUE TITLE
Unable to start MM | New install Rasbian

### ISSUE THREAD

**Issue by sainiaj** [MichMich/MagicMirror#1440]
pi@raspberrypi:~/.npm/_logs $ cat 2018-10-14T04_28_55_553Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.5.0~prestart: magicmirror@2.5.0
6 info lifecycle magicmirror@2.5.0~start: magicmirror@2.5.0
7 verbose lifecycle magicmirror@2.5.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.5.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror@2.5.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.5.0~start: Args: [ '-c', 'sh run-start.sh' ]
11 info lifecycle magicmirror@2.5.0~start: Failed to exec start script
12 verbose stack Error: magicmirror@2.5.0 start: `sh run-start.sh`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:180:13)
12 verbose stack     at maybeClose (internal/child_process.js:936:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid magicmirror@2.5.0
14 verbose cwd /home/pi/MagicMirror
15 verbose Linux 4.14.71-v7+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v9.11.2
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error magicmirror@2.5.0 start: `sh run-start.sh`
23 error spawn ENOENT
24 error Failed at the magicmirror@2.5.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by sainiaj** [comment]
fixed deleted the magicmirror directory and reinstalled via curl cmd
