### ISSUE TITLE
Node module version conflict: [Node.js version using NODE_MODULE_VERSION 67. This version of Node.js requires NODE_MODULE_VERSION 64]

### ISSUE THREAD

**Issue by Dentrax** [MichMich/MagicMirror#1486]
**Platform**: `ArchLinux (npm armv7)`

**Node Version**: `v11.5.0`

**MagicMirror Version**: Latest `master` branch

**Description**: 

I'm trying to create a module via [**serialport**](https://github.com/node-serialport/node-serialport) that will print the information from the serial port to the screen.

**Steps to Reproduce**: 

1. `cd modules/MMM-Test`
2. `vim package.json`

```json
{
    "name": "mmmtest",
    "version": "1.0.0",
    "description": "MagicMirror Module for testing",
    "main": "MMM-Test.js",
    "repository": {
        "type": "git"
    },
    "keywords": [
        "MagicMirror",
        "Module",
        "Test",
        "SerialPort"
    ],
    "dependencies": {
        "serialport": "latest"
    }
}
```

3. `vim node_helper.js`

```js
var NodeHelper = require("node_helper");
var request = require('serialport');
var Readline = require('@serialport/parser-readline');

module.exports = NodeHelper.create({
    start: function() {
        console.log("========== Starting node_helper for module [" + this.name + "]");
        var port = new SerialPort('/dev/ttyUSB0', { baudRate: 9600 });
        const parser = new Readline();
        port.pipe(parser);

        port.on("open", function () {
            console.log('open');
            port.on('data', function(data) {
                console.log(data);
            });
        });
    },
});
```

4. `npm install`
5. `cd ../..`
6. `sh run-start.sh`
7. **BOOOM!**

**Expected Results**: 

The module needs to start listening to the serial port where connected on `ttyXX` port.
(Actually, I expected to be...)

**Actual Results**: 

```
WARNING! Could not load config file. Starting with default configuration. Error found: Error: The module '/home/dentrax/Projects/GitHub/MagicMirror/modules/MMM-Test/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Full error:

```
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/home/dentrax/Projects/GitHub/MagicMirror/modules/MMM-Test/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/home/dentrax/Projects/GitHub/MagicMirror/modules/MMM-Test/node_modules/@serialport/bindings/lib/linux.js:1:191)
Whoops! There was an uncaught exception...
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/home/dentrax/Projects/GitHub/MagicMirror/modules/MMM-Test/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/home/dentrax/Projects/GitHub/MagicMirror/modules/MMM-Test/node_modules/@serialport/bindings/lib/linux.js:1:191)
```

**Configuration**: 

Default `config.js` file. I just only added:

```js
        {
	          module: 'MMM-ArduPort',
	          position: 'bottom_left',
        },
```

**Comment by michael5r** [comment]
The version of Electron that ships with MM 2.5 doesn't support Node 11. Two options:

1) Downgrade to Node 10
2) Use `electron-rebuild` to recompile your NPM package
