### ISSUE TITLE
Installtion failed (MagicMirror dependencies part)

### ISSUE THREAD

**Issue by UtechtDustin** [MichMich/MagicMirror#1759]
**Platform**: Raspbery 3 with raspbian (newest version).

**Node Version**: Make sure it's version 0.12.13 or later.

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).

**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

**Install Log**: 
```
Updating packages ...
Get:1 http://archive.raspberrypi.org/debian buster InRelease [25.2 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf Packages [222 kB]
Fetched 13.3 MB in 19s (680 kB/s)                                                                                                                                                                                 
Reading package lists... Done
Installing helper tools ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
curl is already the newest version (7.64.0-4).
git is already the newest version (1:2.20.1-2).
unzip is already the newest version (6.0-23).
wget is already the newest version (1.20.1-1.1).
wget set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 133 not upgraded.
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v5.1.0
Installed Node version: v10.15.2
No Node.js upgrade necessary.
Check current NPM installation ...
NPM currently installed. Checking version number.
Minimum npm version: V6.0.0
Installed npm version: V5.8.0
npm should be upgraded.
Installing npm ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (5.8.0+ds6-4).
npm set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 133 not upgraded.
npm installation Done!
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 315 (delta 39), reused 193 (delta 21), pack-reused 0
Receiving objects: 100% (315/315), 655.08 KiB | 899.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
Cloning MagicMirror Done!
Installing dependencies ...
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.

> electron-chromedriver@1.8.0 install /root/MagicMirror/node_modules/electron-chromedriver
> node ./download-chromedriver.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/root/MagicMirror/node_modules/electron-chromedriver/download-chromedriver.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-30T09_16_02_651Z-debug.log
```

**Comment by sdetweil** [comment]
try 
```
sudo npm i -g npm
```
 and see if you get an upgraded version... (higher than 5,8.0)

if so, then go to the MagicMirror folder and redo npm install
