### ISSUE TITLE
TypeError: record.start is not a function at GoogleAssistant,startConversation

### ISSUE THREAD

**Issue by limJ224** [MichMich/MagicMirror#1777]
pi@raspberrypi:~/MagicMirror $ npm start

 

> magicmirror@2.9.0 start /home/pi/MagicMirror

> sh run-start.sh

 

Starting MagicMirror: v2.9.0

Loading config ...

Loading module helpers ...

No helper found for module: alert.

No helper found for module: clock.

Initializing new module helper ...

Module helper loaded: calendar

No helper found for module: currentweather.

No helper found for module: weatherforecast.

No helper found for module: MMM-AirQuality.

No helper found for module: compliments.

Initializing new module helper ...

Module helper loaded: newsfeed

Initializing new module helper ...

Module helper loaded: MMM-NotificationTrigger

Initializing new module helper ...

Module helper loaded: MMM-Hotword

Initializing new module helper ...

Module helper loaded: MMM-AssistantMk2

All module helpers loaded.

Starting server on port 8080 ... 

Server started ...

Connecting socket for: calendar

Starting node helper for: calendar

Connecting socket for: newsfeed

Starting module: newsfeed

Connecting socket for: MMM-NotificationTrigger

Connecting socket for: MMM-Hotword

[HOTWORD] MMM-Hotword starts

Connecting socket for: MMM-AssistantMk2

Sockets connected & modules started ...

Launching application.

Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 300000

Create new news fetcher for url: http://fs.jtbc.joins.com/RSS/newsflash.xml - Interval: 300000

[AMK2] Recipe is loaded: hide_and_show_all_modules.js

[AMK2] Recipe is loaded: reboot.js

[AMK2] Recipe is loaded: screen_onoff.js

[AMK2] Recipe is loaded: shutdown.js

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[AMK2] Temporal storage directory is clearing.

[AMK2] assistant ready

[AMK2] Conversation starts.

[AMK2] Started with text query: brief today

{ requestId: 'xx' } { profileFile: 'default.json', lang: 'ko-KR' }

[AMK2] Device Action: { requestId: 'xx' }

[AMK2] Assistant Text Response: 

[AMK2] Conversation Completed

[AMK2] assistant ready

[AMK2] Conversation starts.

Whoops! There was an uncaught exception...

TypeError: record.start is not a function

    at GoogleAssistant.startConversation (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:393:26)

    at GoogleAssistant.emit (events.js:182:13)

    at GoogleAssistant.start (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:38:10)

    at GoogleAssistant.assistant.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:413:17)

    at GoogleAssistant.emit (events.js:182:13)

    at Auth.GoogleAssistant.auth.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:25:10)

    at Auth.emit (events.js:182:13)

    at saveTokens (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:32:10)

    at Auth.process.nextTick (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:92:35)

    at process._tickCallback (internal/process/next_tick.js:61:11)

MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[AMK2] Assistant Text Response: 

[HOTWORD] Detected: smart_mirror

[HOTWORD] stops.

[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }

[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.

    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)

    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)

    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)

    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)

    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)

    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)

    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18

  code: 14,

  metadata:

   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },

  details: 'Service unavailable.' }

[HOTWORD] begins.

[HOTWORD] Detector starts listening.

[AMK2] assistant ready

[AMK2] Conversation starts.

Whoops! There was an uncaught exception...

TypeError: record.start is not a function

    at GoogleAssistant.startConversation (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:393:26)

    at GoogleAssistant.emit (events.js:182:13)

    at GoogleAssistant.start (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:38:10)

    at GoogleAssistant.assistant.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:413:17)

    at GoogleAssistant.emit (events.js:182:13)

    at Auth.GoogleAssistant.auth.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:25:10)

    at Auth.emit (events.js:182:13)

    at saveTokens (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:32:10)

    at Auth.process.nextTick (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:92:35)

    at process._tickCallback (internal/process/next_tick.js:61:11)

MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[AMK2] Assistant Text Response: 

Shutting down server...

Stopping module helper: calendar

Stopping module helper: newsfeed

Stopping module helper: MMM-NotificationTrigger

Stopping module helper: MMM-Hotword

Stopping module helper: MMM-AssistantMk2

how can I solve this problem??

**Comment by sdetweil** [comment]
this should be opened against the MMM-AssistantMk2 module, not the base.

https://github.com/eouia/MMM-AssistantMk2
