### ISSUE TITLE
Cannot read property 'on' 

### ISSUE THREAD

**Issue by jessicanevesmachado** [MichMich/MagicMirror#1809]
Starting MagicMirror: v2.8.0
Whoops! There was an uncaught exception...
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\projetos\teste\-BBX-ESPELHAO\js\electron.js:82:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

can help me?

**Comment by sdetweil** [comment]
can u tell us what version of electron you are running

```
cd  C:\projetos\teste-BBX-ESPELHAO\node_modules\electron
grep version package.json
```

also, v2.9.0 is the current version of MagicMirror

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
