### ISSUE TITLE
magic mirror not starting up

### ISSUE THREAD

**Issue by jtaureau** [MichMich/MagicMirror#2041]
i manually installed and i have done this process a few times now and i know it works but for some reason i cannot get it to load.
i run a,
node v 
and,
npm -v

here are the results:
pi@raspberrypi:~/MagicMirror/MagicMirror $ node v
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi/MagicMirror/MagicMirror/v'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
pi@raspberrypi:~/MagicMirror/MagicMirror $ npm -v
6.14.4

if anyone could shed some light on this that would be great, thank you

**Comment by akki2516** [comment]
try npm start

**Comment by sdetweil** [comment]
what @akki2516  said 
```
cd ~/MagicMirror
npm start 
```

**Comment by jtaureau** [comment]
> what @akki2516 said
> 
> ```
> cd ~/MagicMirror
> npm start 
> ```
Thank you that has worked
