### ISSUE TITLE
Electron blank screen after update for MMM-GoogleAssistant

### ISSUE THREAD

**Issue by blakenorthrup** [MichMich/MagicMirror#2092]
This morning I noticed that my MMM-GoogleAssistant needed an update, so I updated the module, and now get the black electron screen instead of the Magic Mirror screen. If I removed the module from the config, the Mirror comes up correctly, but when I add my config back, it goes black again. I have tried everything, from removing, then reinstalling, npm rebuild, electron rebuild, and nada. Was working fine until then. Any help would be greatly appreciated. See errors below:

 Module helper loaded: MMM-NowPlayingOnSpotify
[2020-07-17 13:07:48.310] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v6.1-linux-arm-glibc
Found: [node-v72-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/grpc_extension.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client_interceptors.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[2020-07-17 13:07:48.311] [LOG]    Loading module helpers ...
[2020-07-17 13:07:48.313] [LOG]    No helper found for module: alert.
[2020-07-17 13:07:48.314] [LOG]    Initializing new module helper ...
[2020-07-17 13:07:48.314] [LOG]    Module helper loaded: updatenotification
[2020-07-17 13:07:48.315] [LOG]    No helper found for module: clock.
[2020-07-17 13:07:48.316] [LOG]    Initializing new module helper ...
[2020-07-17 13:07:48.317] [LOG]    Module helper loaded: calendar
[2020-07-17 13:07:48.318] [LOG]    No helper found for module: MMM-Rainbow.
[2020-07-17 13:07:48.319] [LOG]    No helper found for module: compliments.
[2020-07-17 13:07:48.320] [LOG]    Initializing new module helper ...
[2020-07-17 13:07:48.320] [LOG]    Module helper loaded: MMM-SystemStats
[2020-07-17 13:07:48.321] [LOG]    Initializing new module helper ...
[2020-07-17 13:07:48.322] [LOG]    Module helper loaded: MMM-Remote-Control
[2020-07-17 13:07:48.323] [LOG]    No helper found for module: currentweather.
[2020-07-17 13:07:48.324] [LOG]    No helper found for module: weatherforecast.
[2020-07-17 13:07:48.325] [LOG]    No helper found for module: MMM-EyeCandy.
[2020-07-17 13:07:48.327] [LOG]    Initializing new module helper ...
[2020-07-17 13:07:48.327] [LOG]    Module helper loaded: MMM-NowPlayingOnSpotify
[2020-07-17 13:07:48.352] [ERROR]  App threw an error during load
[2020-07-17 13:07:48.354] [ERROR]  Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v6.1-linux-arm-glibc
Found: [node-v72-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/grpc_extension.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client_interceptors.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
[2020-07-17 13:07:48.356] [ERROR]  Whoops! There was an uncaught exception...
[2020-07-17 13:07:48.357] [ERROR]  Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v6.1-linux-arm-glibc
Found: [node-v72-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/grpc_extension.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client_interceptors.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/@bugsounet/google-assistant/index.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAssistant/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10) {
  code: 'MODULE_NOT_FOUND'
}
[2020-07-17 13:07:48.371] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-07-17 13:07:48.372] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-07-17 13:07:48.539] [LOG]    Launching application.

**Comment by MichMich** [comment]
Please open an issue in the MMM-GoogleAssistant. Thanks.
