### ISSUE TITLE
fork merge failed

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2146]
I am trying to resynch my fork, pull request back

failed 

https://travis-ci.com/github/sdetweil/MagicMirror/jobs/393855912

```
$ yarn danger ci
yarn run v1.3.2
(node:6188) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ /home/travis/build/sdetweil/MagicMirror/node_modules/.bin/danger ci
The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST environmental variable is missing
Without an api token, danger will be unable to comment on a PR
Error:  Error: Cannot use authenticated API requests.
    at Object.getPlatformForEnv (/home/travis/build/sdetweil/MagicMirror/node_modules/danger/distribution/platforms/platform.js:38:11)
    at Object.<anonymous> (/home/travis/build/sdetweil/MagicMirror/node_modules/danger/distribution/commands/ci/runner.js:68:70)
    at step (/home/travis/build/sdetweil/MagicMirror/node_modules/danger/distribution/commands/ci/runner.js:32:23)
    at Object.next (/home/travis/build/sdetweil/MagicMirror/node_modules/danger/distribution/commands/ci/runner.js:13:53)
    at fulfilled (/home/travis/build/sdetweil/MagicMirror/node_modules/danger/distribution/commands/ci/runner.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sdetweil** [comment]
deleted fork, and started over.. all ok, closing, unresolved
