### ISSUE TITLE
After Update to 2.1.6 no start

### ISSUE THREAD

**Issue by TheBassfly** [MichMich/MagicMirror#2608]
Hey there

After updating my Magic Mirror today, it won't start anymore.

When I tried to start it via NPM Start, I got the message:

sh: 1: ./node_modules/.bin/electron: not found

So I tried to install Electron via:

npm install electron@3.0.10

After this, I got this error message:

[01.07.2021 16:37.27.915] [ERROR] App threw an error during load
[01.07.2021 16:37.27.946] [ERROR] TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

What is it, that I'm doing wrong?

Thanks

**Comment by khassel** [comment]
current version is 2.16.0, not 2.1.6

**Comment by MichMich** [comment]
What steps did you take to upgrade?

**Comment by TheBassfly** [comment]
Gut pull & npm install

There was an error with th git pull, so I used git reset --hard and then it worked.

**Comment by MichMich** [comment]
Good to hear! Can I close this issue?

**Comment by TheBassfly** [comment]
No this was the answer to your question how I did the upgrade.

**Comment by MichMich** [comment]
Ah sorry. Thought you fixed it. What version of Node are you running?

**Comment by TheBassfly** [comment]
Node 15.14.0
Npm 7.11.1

**Comment by MichMich** [comment]
Are you running any 3rd party modules?

**Comment by TheBassfly** [comment]
Yes
Calenderext2 and a open weather module.

**Comment by MichMich** [comment]
Try disabling those modules to see if that helps.

**Comment by TheBassfly** [comment]
Are you sure with this? This means for me to del around 80 lines in the config.js. And if this is the problem, the Whole MM would be useless, because all these third party Modules re essential and there no alternatives in the moment.

**Comment by KristjanESPERANTO** [comment]
This is just a test to find out what the problem is. Save your config.js before, so you can easily undo the changes afterwards.

**Comment by MichMich** [comment]
What @KristjanESPERANTO says. It's just to pinpoint the issue. 

You can add comment blocks to make it easier.

**Comment by khassel** [comment]
> npm install electron@3.0.10

we are on v11

**Comment by TheBassfly** [comment]
> > npm install electron@3.0.10
> 
> we are on v11

Thanks for this hint. I updated to v11 and when I start MM again, it show this:


> magicmirror@2.16.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[04.07.2021 12:26.22.738] [ERROR] App threw an error during load
[04.07.2021 12:26.22.750] [ERROR] TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

**Comment by TheBassfly** [comment]
> What @KristjanESPERANTO says. It's just to pinpoint the issue.
> 
> You can add comment blocks to make it easier.

I will try in the next days as I'm niche 24/7 working the MM :). I Keep you updated.

**Comment by TheBassfly** [comment]
> Try disabling those modules to see if that helps.

So, I removed all the third party modules in the config and this happened after "nom start".

> magicmirror@2.16.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[05.07.2021 11:30.20.021] [ERROR] App threw an error during load
[05.07.2021 11:30.20.077] [ERROR] TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

**Comment by MichMich** [comment]
Try removing the node_modules folder and then run `npm install` again.

**Comment by TheBassfly** [comment]
This is the actual Config:



> Try removing the node_modules folder and then run `npm install` again.

Did this but it ended up in the same messages like above.

**Comment by MichMich** [comment]
I don't have a clue what this can be. Can you give a bit more info about your environment?

Os, Version, Hardware, etc.

**Comment by MichMich** [comment]
That should not be a problem. The only thing I can think of is a node version issue. It might be worth trying 14 or 16. If you install node `n` trying this is easy.

**Comment by TheBassfly** [comment]
> That should not be a problem. The only thing I can think of is a node version issue. It might be worth trying 14 or 16. If you install node `n` trying this is easy.

I will give it a try tomorrow.
I just left the versions because some of the homebridge plug-ins awaited lower versions. Let's try it tomorrow.

**Comment by rejas** [comment]
This sounds like this here: https://forum.magicmirror.builders/topic/13362/magic-mirror-2-won-t-start

**Comment by TheBassfly** [comment]
> This sounds like this here: https://forum.magicmirror.builders/topic/13362/magic-mirror-2-won-t-start

Nope
As I'm coming from v. 2.1.5 I did this solution with Git Pull + npm install.

**Comment by TheBassfly** [comment]
> That should not be a problem. The only thing I can think of is a node version issue. It might be worth trying 14 or 16. If you install node `n` trying this is easy.

Okay. I made a switch to Node 14.17.3 and NPM 6.14.13
And made an apt-get Upgrade for the System.

At the Ende same error again

**Comment by sdetweil** [comment]
@TheBassfly you also have to remove node_modules folder and package-lock.json 
and then npm install again

npm7 is the culprit. not passing env correctly. 
I see DISPLAY  missing if I use a script to start mm.   npm start in the mm folder is ok

**Comment by TheBassfly** [comment]
> @TheBassfly you also have to remove node_modules folder and package-lock.json
> and then npm install again
> 
> npm7 is the culprit. not passing env correctly.
> I see DISPLAY missing if I use a script to start mm. npm start in the mm folder is ok

Thanks.
I did it like this but ended up in the same issue. Maybe I have to delete Magic Mirror and have to reinstall everything from scratch.

> magicmirror@2.16.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[06.07.2021 14:22.58.440] [ERROR] App threw an error during load
[06.07.2021 14:22.58.451] [ERROR] TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Bind must be called on a function
    at bind (<anonymous>)
    at /home/pi/MagicMirror/js/logger.js:36:38
    at /home/pi/MagicMirror/js/logger.js:19:20
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:24:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/logger.js:52:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)

**Comment by sdetweil** [comment]
can you do 

grep version ~/MagicMirror/node_modules/console_stamp/package.json

mine on 2.16 is 3.0.2

what modules are you using? MMM-Logging possibly?

**Comment by TheBassfly** [comment]
Mine seems to be 3.0.2 too.

For now I only have standard Module enabled. All third Party modules are removed from the config.json.

**Comment by sdetweil** [comment]
also, could you list the last 2 lines of 

~/MagicMirror/js/logger.js
 mine are 
```
	return logLevel;
});

```
lines 49, and 50, with a trailing blank line

the stack trace shows something from line 52
```
at /home/pi/MagicMirror/js/logger.js:36:38
at /home/pi/MagicMirror/js/logger.js:19:20
at Object. (/home/pi/MagicMirror/js/logger.js:24:3)
at Object. (/home/pi/MagicMirror/js/logger.js:52:3)
```

**Comment by TheBassfly** [comment]
Last 2 Lines:
	return logLevel;
});

There is nothing below Line 50

**Comment by sdetweil** [comment]
ok, one last test.. edit ~/MagicMirror/js/logger.js and comment out line 36 

```
// timeStamp: Function.prototype.bind.call(console.timeStamp, console)
```
I don't know what the side effect will be

what does the config.js logLevel:  setting look like? 
mine in 2.15 looks like 
```
    logLevel: [
      "INFO",
      "LOG",
      "ERROR"
    ],
```

**Comment by TheBassfly** [comment]
> ok, one last test.. edit ~/MagicMirror/js/logger.js and comment out line 36
> 
> ```
> // timeStamp: Function.prototype.bind.call(console.timeStamp, console)
> ```
> 
> I don't know what the side effect will be
> 
> what does the config.js logLevel: setting look like?
> mine in 2.15 looks like
> 
> ```
>     logLevel: [
>       "INFO",
>       "LOG",
>       "ERROR"
>     ],
> ```

After the comment out, the logger.js file seems to be empty now.

**Comment by TheBassfly** [comment]
Okay, it looks like, we are stuck here. 
Is there any special routine to uninstall MagicMirror oder is it just deleting the MagicMirror Folder in the User Folder?

**Comment by TheBassfly** [comment]
When I now run NPM Install I get a bunch of errors:

npm ERR! code ENOSPC
npm ERR! syscall mkdir
npm ERR! path /home/pi/MagicMirror/vendor/node_modules/.staging
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, mkdir '/home/pi/MagicMirror/vendor/node_modules/.staging'
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
npm ERR! code ENOSPC
npm ERR! syscall write
npm ERR! errno -28
npm ERR! nospc ENOSPC: no space left on device, write
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 228
npm ERR! magicmirror@2.16.0 install: `echo "Installing vendor files ...
npm ERR! " && cd vendor && npm install --loglevel=error`
npm ERR! Exit status 228
npm ERR! 
npm ERR! Failed at the magicmirror@2.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by sdetweil** [comment]
just delete the MM folder..

use my install script after.. it didn't have a problem..

wonder what the upgrade script would have done

see 
https://github.com/sdetweil/MagicMirror_scripts

**Comment by sdetweil** [comment]
well, THAT 
npm ERR! nospc ENOSPC: no space left on device, 

is telling.. 

do a df

**Comment by TheBassfly** [comment]
What is DF?

**Comment by sdetweil** [comment]
how old is the SD card... 

sadly the memory technology is write once.  when it comes time to write the same file again, those memory bits are marked used, but the linux file system doesn't know... 

eventually you run out of bits and things become weird.. 
only fix is a new memory card

**Comment by sdetweil** [comment]
>What is DF?

disk full

**Comment by TheBassfly** [comment]
> how old is the SD card...
> 
> sadly the memory technology is write once. when it comes time to write the same file again, those memory bits are marked used, but the linux file system doesn't know...
> 
> eventually you run out of bits and things become weird..
> only fix is a new memory card

It is three years now old with 16GB.

**Comment by sdetweil** [comment]
i think you have hit the used card wall.. 

I have gone thru 10 memory cards, 8, 16 ad 32 gb  in 4 years now.. 

sd cards are great for camera and music, seldom write, lots of read..

on the two systems where I lost the most cards, I have moved to boot from read only sd card,, 
run from ssd. (which has the same memory problem, but WAY more bits)
but I also have a 5 pack or 32g cards ready to go in case..

**Comment by TheBassfly** [comment]
> i think you have hit the used card wall..
> 
> I have gone thru 10 memory cards, 8, 16 and 32 gb in 4 years now..
> 
> sd cards are great for camera and music, seldom write, lots of read..
> 
> on the two systems where I lost the most cards, I have moved to boot from read only sd card,,
> run from ssd. (which has the same memory problem, but WAY more bits)
> but I also have a 5 pack of 32g cards ready to go in case..

I check. I did a cleanup with apt-get. I forgot this after the big upgrade today and after it a got 1.5gb back. I just reinstall MM with your script. Let's see.

**Comment by TheBassfly** [comment]
Allright.
It seemed to be the SD Card Issue.
After Cleanup and reinstall of Magic Mirror, end putting back my Backuped files, everything works again.

Thank you all for the patience.

**Comment by sdetweil** [comment]
well, make a copy asap.. 

the sd card issue is not solvable.
