### ISSUE TITLE
MMM-CalendarWeek

### ISSUE THREAD

**Issue by toven74** [MichMich/MagicMirror#2665]
When I load MM i get this:

Require stack:
- /home/pi/MagicMirror/modules/MMM-CalendarWeek/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CalendarWeek/node_helper.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-CalendarWeek/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]

MM will not load when module is active

**Comment by sdetweil** [comment]
>code: 'MODULE_NOT_FOUND',

a little bit more of the messages with show  you what library is missing

in 2.16 some libraries were removed as they are aged out.. many modules didn't document using them, so this leads to the problem..

do npm install   for each on the MMM-CalendarWeek folder
