### ISSUE TITLE
MMM-Dad-Jokes

### ISSUE THREAD

**Issue by mohawk731** [MichMich/MagicMirror#2688]
I am having a problem where MMM-Dad-Jokes seems to be starting problems with my magic mirror. I had it installed previously, but due to other issues, I had to wipe and rebuild the pi, and am working on getting the magic mirror back up and running for my daughter (yeah, shoulda has a backup but we're here now). I can load and edit other modules, but everytime I load MMM-Dad-Jokes, I only see 'dad joke loading' and if I restart the pi I get the following issues and only see a black screen with no errors from magic mirror. Help please?

pi@raspberrypi:~/MagicMirror $ npm run start

> magicmirror@2.17.1 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[16.10.2021 00:13.41.477] [LOG]   Starting MagicMirror: v2.17.1
[16.10.2021 00:13.41.484] [LOG]   Loading config ...
[16.10.2021 00:13.41.493] [LOG]   Loading module helpers ...
[16.10.2021 00:13.41.496] [LOG]   No helper found for module: alert.
[16.10.2021 00:13.41.518] [LOG]   Initializing new module helper ...
[16.10.2021 00:13.41.520] [LOG]   Module helper loaded: updatenotification
[16.10.2021 00:13.41.523] [LOG]   No helper found for module: clock.
[16.10.2021 00:13.41.771] [LOG]   Initializing new module helper ...
[16.10.2021 00:13.41.773] [LOG]   Module helper loaded: calendar
[16.10.2021 00:13.41.779] [LOG]   No helper found for module: MMM-DailyPokemon.
[16.10.2021 00:13.41.780] [LOG]   No helper found for module: weather.
[16.10.2021 00:13.41.791] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[16.10.2021 00:13.41.793] [LOG]   Loading module helpers ...
[16.10.2021 00:13.41.794] [LOG]   No helper found for module: alert.
[16.10.2021 00:13.41.795] [LOG]   Initializing new module helper ...
[16.10.2021 00:13.41.796] [LOG]   Module helper loaded: updatenotification
[16.10.2021 00:13.41.797] [LOG]   No helper found for module: clock.
[16.10.2021 00:13.41.802] [LOG]   Initializing new module helper ...
[16.10.2021 00:13.41.802] [LOG]   Module helper loaded: calendar
[16.10.2021 00:13.41.804] [LOG]   No helper found for module: MMM-DailyPokemon.
[16.10.2021 00:13.41.805] [LOG]   No helper found for module: weather.
[16.10.2021 00:13.41.807] [ERROR] App threw an error during load
[16.10.2021 00:13.41.810] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[16.10.2021 00:13.41.812] [ERROR] Whoops! There was an uncaught exception...
[16.10.2021 00:13.41.823] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Dad-Jokes/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[16.10.2021 00:13.41.844] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[16.10.2021 00:13.41.846] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[16.10.2021 00:13.42.427] [LOG]   Launching application.

**Comment by mohawk731** [comment]
So simple, but it worked perfectly! I have a lot to learn, thank you!
