### ISSUE TITLE
UnhandledPromiseRejectionWarning on launch

### ISSUE THREAD

**Issue by josselynL** [MichMich/MagicMirror#2717]
**Platform**: RPi 3 on Raspbian

**Node Version**: 16

**MagicMirror Version**: 2.17.1

**Description**: Describe here https://forum.magicmirror.builders/topic/15933/unhandledpromiserejectionwarning-on-launch
UnhandledPromiseRejectionWarning on launch.
No problem when updatenotification is disabled.

```
pi@MagicMirror:~/MagicMirror $ npm run start

> magicmirror@2.17.1 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[29.11.2021 13:35.32.237] [LOG]   Starting MagicMirror: v2.17.1
[29.11.2021 13:35.32.250] [LOG]   Loading config ...
[29.11.2021 13:35.32.263] [LOG]   Loading module helpers ...
[29.11.2021 13:35.32.267] [LOG]   No helper found for module: alert.
[29.11.2021 13:35.32.301] [LOG]   Initializing new module helper ...
[29.11.2021 13:35.32.303] [LOG]   Module helper loaded: updatenotification
[29.11.2021 13:35.32.306] [LOG]   No helper found for module: clock.
[29.11.2021 13:35.32.622] [LOG]   Initializing new module helper ...
[29.11.2021 13:35.32.624] [LOG]   Module helper loaded: calendar
[29.11.2021 13:35.32.626] [LOG]   No helper found for module: weather.
[29.11.2021 13:35.32.629] [LOG]   No helper found for module: compliments.
[29.11.2021 13:35.32.631] [LOG]   No helper found for module: MMM-Traffic.
[29.11.2021 13:35.32.673] [LOG]   Initializing new module helper ...
[29.11.2021 13:35.32.675] [LOG]   Module helper loaded: newsfeed
[29.11.2021 13:35.32.679] [LOG]   Initializing new module helper ...
[29.11.2021 13:35.32.681] [LOG]   Module helper loaded: MMM-Jeedom
[29.11.2021 13:35.32.683] [LOG]   All module helpers loaded.
[29.11.2021 13:35.32.846] [LOG]   Starting server on port 8080 ...
[29.11.2021 13:35.32.872] [LOG]   Server started ...
[29.11.2021 13:35.32.875] [LOG]   Connecting socket for: updatenotification
[29.11.2021 13:35.32.878] [LOG]   Connecting socket for: calendar
[29.11.2021 13:35.32.880] [LOG]   Starting node helper for: calendar
[29.11.2021 13:35.32.881] [LOG]   Connecting socket for: newsfeed
[29.11.2021 13:35.32.883] [LOG]   Starting node helper for: newsfeed
[29.11.2021 13:35.32.885] [LOG]   Connecting socket for: MMM-Jeedom
[29.11.2021 13:35.32.886] [LOG]   Sockets connected & modules started ...
[29.11.2021 13:35.33.271] [LOG]   Launching application.
[29.11.2021 13:35.37.108] [LOG]   Create new calendarfetcher for url: http://p28-caldav.icloud.com/published/2/XXX - Interval: 300000
[29.11.2021 13:35.37.170] [LOG]   Create new calendarfetcher for url: http://p28-caldav.icloud.com/published/2/XXX - Interval: 300000
[29.11.2021 13:35.37.420] [LOG]   Create new newsfetcher for url: https://www.ladepeche.fr/rss.xml - Interval: 300000
[29.11.2021 13:35.37.438] [INFO]  Checking git for module: default
[29.11.2021 13:35.37.481] [INFO]  Checking git for module: MMM-Traffic
[29.11.2021 13:35.37.504] [INFO]  Checking git for module: MMM-Jeedom
[29.11.2021 13:35.38.791] [INFO]  Calendar-Fetcher: Broadcasting 10 events.
[29.11.2021 13:35.38.845] [INFO]  Newsfeed-Fetcher: Broadcasting 100 items.
[29.11.2021 13:35.43.285] [INFO]  Calendar-Fetcher: Broadcasting 10 events.
[29.11.2021 13:35.44.412] [ERROR] (node:3953) UnhandledPromiseRejectionWarning: Error: Command failed: cd /home/pi/MagicMirror/ && git fetch --dry-run
error: droits insuffisants pour ajouter un objet à la base de données .git/objects du dépôt
fatal: failed to write object
fatal: échec de unpack-objects

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
(Use `electron --trace-warnings ...` to show where the warning was created)
[29.11.2021 13:35.44.416] [ERROR] (node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[29.11.2021 13:35.44.418] [ERROR] (node:3953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
```

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!
```
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2021.11.29 14:50:57 =~=~=~=~=~=~=~=~=~=~=~=
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "localhost", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "fr",
	locale: "fr",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar",
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Calendrier",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						//url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"
						url: 'webcal://p28-XXX'
					},
					{
						symbol: "birthday-cake",
						url: 'webcal://p28-XXX'
					},
				]
			}
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "XXX",
				locationID: "XXX", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "XXX"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Météo à ",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "XXX",
				locationID: "XXX", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "XXX"
			}
	},
                {
                        module: 'compliments',
                        position: 'lower_third',
                        config: {
                                remoteFile: 'compliments.json'
				//file stored in modules/compliments/compliments.json
				}
                },
{
                module: "MMM-Traffic",
                position: "bottom_left",
                config: {
                               accessToken: "XXX",
	                       originCoords: "XXX",
                               destinationCoords: "XXX",
                               firstLine: "{duration} mins",
                               secondLine: "XXX",
                               //days: [0,1,2,3,4],
                               //hoursStart: "06:30",
                               //hoursEnd: "15:00"
                }
},

{
                module: "MMM-Traffic",
                position: "bottom_left",
                config: {
                               accessToken: "XXX",
                               originCoords: "XXX",
                               destinationCoords: "XXX",
                               firstLine: "{duration} mins",
                               secondLine: "XXX",
			       //days: [0,1,2,3,4],
                               //hoursStart: "06:30",
                               //hoursEnd: "15:00"
                }
},

		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "La depeche",
						url: "https://www.ladepeche.fr/rss.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
			module: 'MMM-Jeedom',
			header: 'Informations Maison',
			position: "bottom_right",
			config: {
				updateInterval: 3000,
			      	jeedomAPIKey: "XXX", 
				jeedomURL: "XXX",
				jeedomPORT: XXX,
				jeedomHTTPS: XXX,
				jeedomAPIPath: "/core/api/jeeApi.php",
				sensors: [ XXX (about 15 sensors) ]
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Additional Notes**: disabled the module 'updatenotification' makes the errors disappear

**Comment by rejas** [comment]
Mhh... maybe the MMM-Jeedom or the MMM-Trafik module dont have a git repository associated with them? Is the error still happening when you enable the updatenotification and disable those two (or one of them)?

**Comment by josselynL** [comment]
Ok just found the problem while solve another.
The owner of MagicMirror folder was root, i don't know why.

I've changed this for pi with
```
cd ~
sudo chown -R pi MagicMirror
```
And no more error...

**Comment by sdetweil** [comment]
@josselynL probably did sudo git clone
