### ISSUE TITLE
Network Connection is unable to get to speed test

### ISSUE THREAD

**Issue by richtw370** [MichMich/MagicMirror#3012]
I am running magic mirror on my Pi 400

It has been running without a problem for over a year.  I  made no changes.

I noticed that the network connection module is not loading any more and I see the following:

[2023-01-16 18:09:59.160] [ERROR]  Whoops! There was an uncaught exception...
[2023-01-16 18:09:59.161] [ERROR]  Error: No server found, verify your proxy/network
    at gotServers (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/speedtest-net/index.js:621:25)
    at /home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/speedtest-net/index.js:107:16
    at /home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/speedtest-net/index.js:301:7
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:200:13)
    at SAXParser.onclosetag (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/pi/MagicMirror/modules/MMM-NetworkConnection/node_modules/sax/lib/sax.js:1436:13)
[2023-01-16 18:09:59.166] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2023-01-16 18:09:59.166] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Node Version**: I just upgraded to node 10.23 (along with  upgrading NPM to 6.14) and restarted and still get the same problem

**MagicMirror² Version**: 2.13

**Steps to Reproduce**: use NPM start

**Expected Results**: module should start up and show ping, upload and download speed

**Actual Results**: Mirror just shows "loading" where this module should display

**Configuration**: config.js attached

[config.txt](https://github.com/MichMich/MagicMirror/files/10429991/config.txt)

**Comment by khassel** [comment]
This repo is only for issues with mm core or the default modules. We don't support foreign modules here, please open an issue in the gitgub repository of the module or ask in the forum (Link on main page of this repo).
