### ISSUE TITLE
install problems for several times,..

### ISSUE THREAD

**Issue by Binog** [MichMich/MagicMirror#724]
**Platform**: Raspberry Pi 3

**Node Version**: v4.3.0

**MagicMirror Version**: Guess the the newer JavaScript version (v2).

**Description**: I followed this guide after having it a third or fourth time installed:
`https://forum.magicmirror.builders/topic/236/complete-setup-tutorial/6`

**Steps to Reproduce**: Auto installation like in the guide above.

**Expected Results**: a clean install and the default screen

**Actual Results**: 
in the automatic installation at first I see this:

```
Cloning MagicMirror Done!
Installing dependencies ...
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global colorguard@1.2.0 should be installed with -g

> electron@1.4.15 postinstall /home/pi/MagicMirror/node_modules/electron
> node install.js
...
├─┬ UNMET PEER DEPENDENCY grunt@1.0.1
...
npm WARN grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.

```
 Then I  install the above all to gather without errors..

Then I installed: 

```
sudo npm install -g grunt-yamllint
/usr/lib
├── UNMET PEER DEPENDENCY grunt@~0.4.0
└─┬ grunt-yamllint@0.2.0 
  ├── async@0.9.2 
  ├─┬ chalk@0.5.1 
  │ ├── ansi-styles@1.1.0 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@0.1.0 
  │ │ └── ansi-regex@0.2.1 
  │ ├── strip-ansi@0.3.0 
  │ └── supports-color@0.2.0 
  └─┬ js-yaml@3.8.1 
    ├─┬ argparse@1.0.9 
    │ └── sprintf-js@1.0.3 
    └── esprima@3.1.3 

npm WARN grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.
```
and again

```
sudo npm install -g grunt@~0.4.0
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
- ansi-regex@2.1.1 node_modules/grunt/node_modules/ansi-regex
- ansi-styles@2.2.1 node_modules/grunt/node_modules/ansi-styles
- array-find-index@1.0.2 node_modules/grunt/node_modules/array-find-index
- balanced-match@0.4.2 node_modules/grunt/node_modules/balanced-match
- builtin-modules@1.1.1 node_modules/grunt/node_modules/builtin-modules
- camelcase@2.1.1 node_modules/grunt/node_modules/camelcase
- concat-map@0.0.1 node_modules/grunt/node_modules/concat-map
- brace-expansion@1.1.6 node_modules/grunt/node_modules/brace-expansion
- currently-unhandled@0.4.1 node_modules/grunt/node_modules/currently-unhandled
- decamelize@1.2.0 node_modules/grunt/node_modules/decamelize
- escape-string-regexp@1.0.5 node_modules/grunt/node_modules/escape-string-regexp
- fs.realpath@1.0.0 node_modules/grunt/node_modules/fs.realpath
- get-stdin@4.0.1 node_modules/grunt/node_modules/get-stdin
- grunt-known-options@1.1.0 node_modules/grunt/node_modules/grunt-known-options
- lodash@4.3.0 node_modules/grunt/node_modules/grunt-legacy-util/node_modules/lodash
- has-ansi@2.0.0 node_modules/grunt/node_modules/has-ansi
- hosted-git-info@2.2.0 node_modules/grunt/node_modules/hosted-git-info
- is-arrayish@0.2.1 node_modules/grunt/node_modules/is-arrayish
- error-ex@1.3.0 node_modules/grunt/node_modules/error-ex
- is-builtin-module@1.0.0 node_modules/grunt/node_modules/is-builtin-module
- is-utf8@0.2.1 node_modules/grunt/node_modules/is-utf8
- isexe@1.1.2 node_modules/grunt/node_modules/isexe
- map-obj@1.0.1 node_modules/grunt/node_modules/map-obj
- camelcase-keys@2.1.0 node_modules/grunt/node_modules/camelcase-keys
- minimist@1.2.0 node_modules/grunt/node_modules/minimist
- number-is-nan@1.0.1 node_modules/grunt/node_modules/number-is-nan
- is-finite@1.0.2 node_modules/grunt/node_modules/is-finite
- object-assign@4.1.1 node_modules/grunt/node_modules/object-assign
- parse-json@2.2.0 node_modules/grunt/node_modules/parse-json
- path-is-absolute@1.0.1 node_modules/grunt/node_modules/path-is-absolute
- pify@2.3.0 node_modules/grunt/node_modules/pify
- pinkie@2.0.4 node_modules/grunt/node_modules/pinkie
- pinkie-promise@2.0.1 node_modules/grunt/node_modules/pinkie-promise
- path-exists@2.1.0 node_modules/grunt/node_modules/path-exists
- find-up@1.1.2 node_modules/grunt/node_modules/find-up
- path-type@1.1.0 node_modules/grunt/node_modules/path-type
- repeating@2.0.1 node_modules/grunt/node_modules/repeating
- indent-string@2.1.0 node_modules/grunt/node_modules/indent-string
- resolve@1.1.7 node_modules/grunt/node_modules/resolve
- semver@5.3.0 node_modules/grunt/node_modules/semver
- signal-exit@3.0.2 node_modules/grunt/node_modules/signal-exit
- loud-rejection@1.6.0 node_modules/grunt/node_modules/loud-rejection
- spdx-expression-parse@1.0.4 node_modules/grunt/node_modules/spdx-expression-parse
- spdx-license-ids@1.2.2 node_modules/grunt/node_modules/spdx-license-ids
- spdx-correct@1.0.2 node_modules/grunt/node_modules/spdx-correct
- sprintf-js@1.0.3 node_modules/grunt/node_modules/sprintf-js
- strip-ansi@3.0.1 node_modules/grunt/node_modules/strip-ansi
- strip-bom@2.0.0 node_modules/grunt/node_modules/strip-bom
- load-json-file@1.1.0 node_modules/grunt/node_modules/load-json-file
- strip-indent@1.0.1 node_modules/grunt/node_modules/strip-indent
- redent@1.0.0 node_modules/grunt/node_modules/redent
- supports-color@2.0.0 node_modules/grunt/node_modules/supports-color
- chalk@1.1.3 node_modules/grunt/node_modules/chalk
- trim-newlines@1.0.0 node_modules/grunt/node_modules/trim-newlines
- validate-npm-package-license@3.0.1 node_modules/grunt/node_modules/validate-npm-package-license
- normalize-package-data@2.3.5 node_modules/grunt/node_modules/normalize-package-data
- read-pkg@1.1.0 node_modules/grunt/node_modules/read-pkg
- read-pkg-up@1.0.1 node_modules/grunt/node_modules/read-pkg-up
- meow@3.7.0 node_modules/grunt/node_modules/meow
- wrappy@1.0.2 node_modules/grunt/node_modules/wrappy
- once@1.4.0 node_modules/grunt/node_modules/once
- inflight@1.0.6 node_modules/grunt/node_modules/inflight
- grunt-cli@1.2.0 node_modules/grunt/node_modules/grunt-cli
/usr/lib
└─┬ grunt@0.4.5 
  ├── async@0.1.22 
  ├── coffee-script@1.3.3 
  ├── colors@0.6.2 
  ├── dateformat@1.0.2-1.2.3 
  ├─┬ findup-sync@0.1.3 
  │ ├─┬ glob@3.2.11 
  │ │ └── minimatch@0.3.0 
  │ └── lodash@2.4.2 
  ├─┬ glob@3.1.21 
  │ ├── graceful-fs@1.2.3 
  │ └── inherits@1.0.2 
  ├─┬ grunt-legacy-log@0.1.3 
  │ ├─┬ grunt-legacy-log-utils@0.1.1 
  │ │ ├── lodash@2.4.2 
  │ │ └── underscore.string@2.3.3 
  │ ├── lodash@2.4.2 
  │ └── underscore.string@2.3.3 
  ├── grunt-legacy-util@0.2.0 
  ├── iconv-lite@0.2.11 
  ├─┬ js-yaml@2.0.5 
  │ ├─┬ argparse@0.1.16 
  │ │ ├── underscore@1.7.0 
  │ │ └── underscore.string@2.4.0 
  │ └── esprima@1.0.4 
  ├── lodash@0.9.2 
  ├─┬ minimatch@0.2.14 
  │ ├── lru-cache@2.7.3 
  │ └── sigmund@1.0.1 
  ├── nopt@1.0.10 
  ├── underscore.string@2.2.1 
  └── which@1.0.9 

```

This is what I see: npm start

```
> magicmirror@2.1.0 start /home/pi/MagicMirror
> electron js/electron.js


npm ERR! Linux 4.4.49-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "-dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.1.0 start: `electron js/electron.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magicmirror@2.1.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2017-02-19T14_18_34_280Z-debug.log

**Configuration**: actual at the moment none. Cause I just installed.


**/home/pi/.npm/_logs/2017-02-19T14_18_34_280Z-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'bugs', 'magicmirror' ]
2 info using npm@4.3.0
3 info using node@v6.9.5
4 silly fetchPackageMetaData magicmirror
5 silly fetchNamedPackageData magicmirror
6 silly mapToRegistry name magicmirror
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'magicmirror',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'magicmirror',
9 silly mapToRegistry   name: 'magicmirror',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/magicmirror
11 verbose request uri https://registry.npmjs.org/magicmirror
12 verbose request no auth needed
13 info attempt registry request try #1 at 15:15:50
14 verbose request id e516b09ba089b372
15 http request GET https://registry.npmjs.org/magicmirror
16 http 200 https://registry.npmjs.org/magicmirror
17 verbose headers { server: 'nginx/1.10.1',
17 verbose headers   'content-type': 'application/json',
17 verbose headers   'last-modified': 'Wed, 30 Mar 2016 10:44:27 GMT',
17 verbose headers   etag: 'W/"56fbae0b-bef"',
17 verbose headers   'content-encoding': 'gzip',
17 verbose headers   'cache-control': 'max-age=300',
17 verbose headers   'content-length': '1289',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Sun, 19 Feb 2017 14:15:50 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-ams4450-AMS',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1487513750.882783,VS0,VE22',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 200,
18 silly get   { server: 'nginx/1.10.1',
18 silly get     'content-type': 'application/json',
18 silly get     'last-modified': 'Wed, 30 Mar 2016 10:44:27 GMT',
18 silly get     etag: 'W/"56fbae0b-bef"',
18 silly get     'content-encoding': 'gzip',
18 silly get     'cache-control': 'max-age=300',
18 silly get     'content-length': '1289',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Sun, 19 Feb 2017 14:15:50 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-ams4450-AMS',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1487513750.882783,VS0,VE22',
18 silly get     vary: 'Accept-Encoding' } ]
19 verbose get saving magicmirror to /home/pi/.npm/registry.npmjs.org/magicmirror/.cache.json
20 verbose correctMkdir /home/pi/.npm correctMkdir not in flight; initializing
21 silly bugs url https://github.com/MichMich/MagicMirror/issues
22 verbose stack Error: Command failed: xdg-open https://github.com/MichMich/MagicMirror/issues
22 verbose stack /usr/bin/xdg-open: 1: eval: www-browser: not found
22 verbose stack /usr/bin/xdg-open: 1: eval: links2: not found
22 verbose stack /usr/bin/xdg-open: 1: eval: elinks: not found
22 verbose stack /usr/bin/xdg-open: 1: eval: links: not found
22 verbose stack /usr/bin/xdg-open: 1: eval: lynx: not found
22 verbose stack /usr/bin/xdg-open: 1: eval: w3m: not found
22 verbose stack xdg-open: no method available for opening 'https://github.com/MichMich/MagicMirror/issues'
22 verbose stack
22 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
22 verbose stack     at emitTwo (events.js:106:13)
22 verbose stack     at ChildProcess.emit (events.js:191:7)
22 verbose stack     at maybeClose (internal/child_process.js:877:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
23 verbose cwd /home/pi/MagicMirror
24 error Linux 4.4.49-v7+
25 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "magicmirror"
26 error node v6.9.5
27 error npm  v4.3.0
28 error code 3
29 error Command failed: xdg-open https://github.com/MichMich/MagicMirror/issues
29 error /usr/bin/xdg-open: 1: eval: www-browser: not found
29 error /usr/bin/xdg-open: 1: eval: links2: not found
29 error /usr/bin/xdg-open: 1: eval: elinks: not found
29 error /usr/bin/xdg-open: 1: eval: links: not found
29 error /usr/bin/xdg-open: 1: eval: lynx: not found
29 error /usr/bin/xdg-open: 1: eval: w3m: not found
29 error xdg-open: no method available for opening 'https://github.com/MichMich/MagicMirror/issues'
30 error If you need help, you may report this error at:
30 error     <https://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]

```

What Am I doing wrong??

**Comment by nhubbard** [comment]
@Binog You can ignore the unmet peer dependency; it is a result of our development process. Your mirror should work with any of the errors above.

**Comment by Binog** [comment]
Thanks for replying. Well I installed it as mentioned several times, cause the mirror quits unexpectedly after several minutes. now it seems to work. except that some modules do not work,. which worked in the first place. Wonderground, airquality, pinhole-stats,.. could those errors above be the cause. didn't change the config...

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by Binog** [comment]
well, I still don't know weither I should install the npm packages (grant,..) manually, or if I can totally ignore this. If so, I think there shouldn't be an error message during installation,.. even if this is a result of you development process.. it really confuses me (and I guess others,..)
