### ISSUE TITLE
update errors

### ISSUE THREAD

**Issue by robertoOk** [MichMich/MagicMirror#842]
hi, i've just update magic mirror to version 2.1.1 and it gave me those errors, what can i do with this?

pi@raspberrypi:~/MagicMirror2 $ npm start

> magicmirror@2.1.1 start /home/pi/MagicMirror2
> sh run-start.sh

Starting MagicMirror: v2.1.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing mm-music-player module helper ...
WARNING! Could not load config file. Starting with default configuration. Error found: TypeError: m.loaded is not a function
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing mm-music-player module helper ...
App threw an error during load
TypeError: m.loaded is not a function
    at loadModule (/home/pi/MagicMirror2/js/app.js:144:6)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
Whoops! There was an uncaught exception...
TypeError: m.loaded is not a function
    at loadModule (/home/pi/MagicMirror2/js/app.js:144:6)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror2/js/app.js:161:5)
    at /home/pi/MagicMirror2/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror2/js/app.js:146:4)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by MichMich** [comment]
There is an issue with the 'mm-music-player' module. Not with the Mirror's Core.

Please refer to the builder of that module or http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
